# Generated by Django 4.2.4 on 2023-09-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_entry_next_pme_date_entry_next_vt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_pme_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_vt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last VT Date'),
        ),
    ]
