# Generated by Django 4.2.4 on 2023-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_alter_entry_last_pme_date_alter_entry_last_vt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
